# Generated by Django 2.1.3 on 2018-12-28 18:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditedBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_vote', models.TextField()),
                ('vote_hash', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CastVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', django.contrib.postgres.fields.jsonb.JSONField()),
                ('vote_hash', models.CharField(max_length=100)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('cast_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('public_key', models.CharField(max_length=250)),
                ('private_key', models.CharField(max_length=250)),
                ('cred_set', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('cast_votes', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(default=None, null=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('registration_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_ends_at', models.DateTimeField(default=None, null=True)),
                ('complaint_period_ends_at', models.DateTimeField(default=None, null=True)),
                ('tallying_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_started_at', models.DateTimeField(default=None, null=True)),
                ('voting_extended_until', models.DateTimeField(default=None, null=True)),
                ('voting_ended_at', models.DateTimeField(default=None, null=True)),
                ('tallying_started_at', models.DateTimeField(default=None, null=True)),
                ('tallying_finished_at', models.DateTimeField(default=None, null=True)),
                ('tallies_combined_at', models.DateTimeField(default=None, null=True)),
                ('result_released_at', models.DateTimeField(default=None, null=True)),
                ('voters_hash', models.CharField(max_length=100, null=True)),
                ('encrypted_tally', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('help_email', models.EmailField(max_length=254, null=True)),
                ('election_info_url', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_description', models.TextField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=250)),
                ('private_key_hash', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250)),
                ('pok', models.CharField(max_length=250)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_name', models.CharField(max_length=200)),
                ('voter_email', models.CharField(max_length=250)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('auth_key_hash', models.CharField(max_length=250, null=True)),
                ('auth_for', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Question'),
        ),
        migrations.AddField(
            model_name='castvote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Election'),
        ),
        migrations.AddField(
            model_name='auditedballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.Election'),
        ),
        migrations.AlterUniqueTogether(
            name='trustee',
            unique_together={('election', 'email')},
        ),
    ]
