# Generated by Django 2.1.3 on 2019-01-08 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=250)),
                ('private_key_hash', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='election',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
