# Generated by Django 2.1.3 on 2019-01-08 14:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20190108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='encrypted_tally',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
