# Generated by Django 2.1.3 on 2019-01-08 23:40

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_auto_20190108_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='private_key',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=computed_property.fields.ComputedCharField(compute_from='key_generation', editable=False, max_length=4000),
        ),
    ]
