# Generated by Django 2.1.3 on 2019-01-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20190108_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='election',
            name='public_key',
        ),
    ]
