# Generated by Django 2.1.3 on 2019-01-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_auto_20190108_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='private_key',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='public_key',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
