# Generated by Django 2.1.3 on 2019-01-09 00:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0006_auto_20190108_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='private_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
