# Generated by Django 2.1.3 on 2019-01-09 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0007_auto_20190108_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustee',
            old_name='private_key_hash',
            new_name='trustee_private_key_hash',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='public_key',
        ),
        migrations.AddField(
            model_name='trustee',
            name='trustee_private_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='trustee_public_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
