# Generated by Django 2.1.3 on 2019-01-09 22:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20190109_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='desig_key_hash',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='public_auth_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='public_desig_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationteller',
            name='registration_public_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
